version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: backend_postgres
    environment:
      POSTGRES_DB: backend_postgres
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend123
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U backend_user -d backend_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
